# Generated by Django 3.0.3 on 2020-02-16 04:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('duration', models.IntegerField(blank=True, default=0, help_text='duration in seconds')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
